### ISSUE TITLE
Some TV shows are not displayed

### ISSUE THREAD

**Issue by MrReSc** [goggle/plugin.video.srfplaytv#5]
For example, the TV show "[Alisa - Folge deinem Herzen](https://www.srf.ch/play/tv/sendung/alisa-folge-deinem-herzen?id=80f42b1e-8940-4627-98ee-e8fda96a6042)" is available on the Play SRF website, but is not shown in your plugin.

![2018-12-05_13-46-01](https://user-images.githubusercontent.com/24952268/49514370-271f2180-f894-11e8-9eef-95d74e3d8a9a.png)

**Comment by goggle** [comment]
The Show "Alisa - Folge deinem Herzen" is currently not listed in https://www.srf.ch/play/tv/sendungen?index=all, which is the source of the plugin's show list. It's currently also not listed in the date overview (https://www.srf.ch/play/tv/sendungen-nach-datum?date=05-12-2018).

So it is not the plugin's fault, and I don't have an idea how to solve this at the moment. It is possible that SRF updates the file http://il.srgssr.ch/integrationlayer/1.0/ue/srf/tv/assetGroup/editorialPlayerAlphabetical.json only once per week, but as soon as this happens, the show should be listed again in the plugin.

**Comment by MrReSc** [comment]
I have contacted SRF. Now it works again.

In contact with the SRF developer, I found out that you are using an old data interface (ILv1) for your plugin. This interface will no longer be developed and will probably be discontinued at some point. There is a new API from SRF see [https://developer.srgssr.ch/apis](https://developer.srgssr.ch/apis) here.

Thanks for your work!

**Comment by goggle** [comment]
Yes, I know about the SRG developer API. Unfortunately, I don't think that can be used for this Kodi plugin. Each access to their API (even those requests which return a list of available shows etc.) requires a registered API key. I could apply for such an API key, but I cannot use it in this plugin, because you are not allowed to give your API key to anybody (https://developer.srgssr.ch/sites/default/files/Terms_SRGSSR_APIPortal_ENG.pdf). Using their API in this plugin would mean, that every user of  this plugin has access to my keys, which is forbidden... So unfortunately I don't see a solution to use their really nice looking developers API for this project.

I think this plugin uses the old ILv1 only once for accessing all the available SRF shows, because I could not find a equivalent ILv2 call to do this. Everywhere else ILv2 is used, which is also used by the SRF website.
